/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Drive_DC_Motor_In2_aliases.h"
#include "Drive_DC_Motor_In2.h"
#include "Drive_DC_Motor_In1_aliases.h"
#include "Drive_DC_Motor_In1.h"
#include "Clock.h"
#include "Drive_DC_Motor_PWM.h"
#include "RC_Ch1_aliases.h"
#include "RC_Ch1.h"
#include "RC_Ch1_Timer.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "RC_Ch2_Timer_Interrupt.h"
#include "RC_Ch2_aliases.h"
#include "RC_Ch2.h"
#include "RC_Ch2_Timer.h"
#include "Clock_Millis_Interrupt.h"
#include "Clock_Millis.h"
#include "RC_Ch1_Timer_Interrupt.h"
#include "RC_Ch4_Timer.h"
#include "RC_Ch4_aliases.h"
#include "RC_Ch4.h"
#include "RC_Ch4_Timer_Interrupt.h"
#include "RC_Ch3_Timer.h"
#include "RC_Ch3_aliases.h"
#include "RC_Ch3.h"
#include "RC_Ch3_Timer_Interrupt.h"
#include "Flywheel_DC_Motor_In1_aliases.h"
#include "Flywheel_DC_Motor_In1.h"
#include "Pendulum_DC_Motor_In1_aliases.h"
#include "Pendulum_DC_Motor_In1.h"
#include "Pendulum_DC_Motor_In2_aliases.h"
#include "Pendulum_DC_Motor_In2.h"
#include "Pendulum_DC_Motor_PWM.h"
#include "Flywheel_DC_Motor_In2_aliases.h"
#include "Flywheel_DC_Motor_In2.h"
#include "Flywheel_DC_Motor_PWM.h"
#include "MPU6050_SDA_aliases.h"
#include "MPU6050_SDA.h"
#include "MPU6050_SCL_aliases.h"
#include "MPU6050_SCL.h"
#include "MPU6050_I2C.h"
#include "MPU6050_I2C_PVT.h"
#include "Drive_DC_Motor_Quad_Dec.h"
#include "Drive_DC_Motor_Enc_A_aliases.h"
#include "Drive_DC_Motor_Enc_A.h"
#include "Drive_DC_Motor_Enc_B_aliases.h"
#include "Drive_DC_Motor_Enc_B.h"
#include "Pendulum_DC_Motor_Quad_Dec.h"
#include "Pendulum_DC_Motor_Enc_A_aliases.h"
#include "Pendulum_DC_Motor_Enc_A.h"
#include "Pendulum_DC_Motor_Enc_B_aliases.h"
#include "Pendulum_DC_Motor_Enc_B.h"
#include "Status_LED_aliases.h"
#include "Status_LED.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "Drive_DC_Motor_Quad_Dec_Cnt16.h"
#include "Pendulum_DC_Motor_Quad_Dec_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

